### PR TITLE
Add `CiliumEniModeClusterBuilder`

### PR DESCRIPTION
**Pull request by AndiDog**
### What does this PR do?

Towards https://github.com/giantswarm/roadmap/issues/2563

### Checklist

- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by AverageMarcus** [comment]
@AndiDog Do we really need a whole builder for this? This is something that could be done in a single test suite if that's the intention. Do you expect this to be used outside of `cluster-test-suites`? (e.g. with app tests and with CNCF Conformance)

**Comment by AndiDog** [comment]
> @AndiDog Do we really need a whole builder for this? This is something that could be done in a single test suite if that's the intention. Do you expect this to be used outside of `cluster-test-suites`? (e.g. with app tests and with CNCF Conformance)

I wasn't sure. We have a builder for private clusters, for instance. Where else do we use these builders overall? I'm fine to instead use the standard builder and overriding the 2 Helm values in `cluster-test-suites`.

**Comment by AverageMarcus** [comment]
We have a different builder for private because it also requires a different MC. 

I think until we need to use this cluster configuration with anything other than cluster-test-suites it might be better to just have it as override values in the test suite in cluster-test-suites. It's easy enough to move it out if and when we do need to. 😄 

That also means that you don't need to deal with new releases of this module to be able to make changes to it in cluster-test-suites.

What do you think? I'm happy either way, just sharing my opinion.

**Comment by AndiDog** [comment]
Yep makes sense.

**Pull request closed without merging**
